apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  selector:
    app: nginx-test
  # type: LoadBalancer
  # type: ClusterIP
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: serviceport