---
apiVersion: v1
kind: Namespace
metadata:
  name: example

---
apiVersion: v1
data:
  PGHOST: "3.86.88.152"
  PGUSER: "bukanebi"
  PGDATABASE: "sample"
  PGPASSWORD: "bukanebi"
  PGPORT: "5432"
  SERVICEPORT: "9000"
  MODE: "Dev"

kind: ConfigMap
metadata:
  name: test-service
  namespace: example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  namespace: example
spec:
  selector:
    matchLabels:
      app: user-services
  replicas: 2
  template:
    metadata:
      labels:
        app: user-services
    spec:
      containers:
        - name: user-service
          image: bukanebi/user-service-image
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: test-service

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: example
  labels:
    app: user-services
spec:
  selector:
    app: user-services
  # type: LoadBalancer
  # type: ClusterIP
  type: NodePort
  ports:
    - port: 8081
      targetPort: 9000
      nodePort: 30581
      protocol: TCP
      name: serviceport
